### ISSUE TITLE
[Request feature] Manage auto run registry keys

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/winebridge#1]
## Registry keys
- `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services`
- `HKEY_USERS\S-1-5-21-0-0-0-1000\Software\Microsoft\Windows\CurrentVersion\Run`
- `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`
- `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run`
- `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce`

## Methods
- [x] LIST
- [ ] ~~ADD~~
- [ ] ~~REMOVE~~
- [x] MODIFY

**Comment by pietrodicaprio** [comment]
ADD and REMOVE not anymore in scope for next release
